// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: service.proto

package sidecar_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParentService_RegisterSidecar_FullMethodName   = "/aiquery.v1.ParentService/RegisterSidecar"
	ParentService_Heartbeat_FullMethodName         = "/aiquery.v1.ParentService/Heartbeat"
	ParentService_UnregisterSidecar_FullMethodName = "/aiquery.v1.ParentService/UnregisterSidecar"
)

// ParentServiceClient is the client API for ParentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ParentService is the gRPC service that sidecars connect to
// Sidecars call these methods for lifecycle management
type ParentServiceClient interface {
	// RegisterSidecar is called when a sidecar starts up
	RegisterSidecar(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat is called periodically to maintain connection
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// UnregisterSidecar is called when a sidecar shuts down gracefully
	UnregisterSidecar(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type parentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParentServiceClient(cc grpc.ClientConnInterface) ParentServiceClient {
	return &parentServiceClient{cc}
}

func (c *parentServiceClient) RegisterSidecar(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ParentService_RegisterSidecar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ParentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentServiceClient) UnregisterSidecar(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, ParentService_UnregisterSidecar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParentServiceServer is the server API for ParentService service.
// All implementations must embed UnimplementedParentServiceServer
// for forward compatibility.
//
// ParentService is the gRPC service that sidecars connect to
// Sidecars call these methods for lifecycle management
type ParentServiceServer interface {
	// RegisterSidecar is called when a sidecar starts up
	RegisterSidecar(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat is called periodically to maintain connection
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// UnregisterSidecar is called when a sidecar shuts down gracefully
	UnregisterSidecar(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	mustEmbedUnimplementedParentServiceServer()
}

// UnimplementedParentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParentServiceServer struct{}

func (UnimplementedParentServiceServer) RegisterSidecar(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSidecar not implemented")
}
func (UnimplementedParentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedParentServiceServer) UnregisterSidecar(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterSidecar not implemented")
}
func (UnimplementedParentServiceServer) mustEmbedUnimplementedParentServiceServer() {}
func (UnimplementedParentServiceServer) testEmbeddedByValue()                       {}

// UnsafeParentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParentServiceServer will
// result in compilation errors.
type UnsafeParentServiceServer interface {
	mustEmbedUnimplementedParentServiceServer()
}

func RegisterParentServiceServer(s grpc.ServiceRegistrar, srv ParentServiceServer) {
	// If the following call panics, it indicates UnimplementedParentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParentService_ServiceDesc, srv)
}

func _ParentService_RegisterSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).RegisterSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_RegisterSidecar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).RegisterSidecar(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParentService_UnregisterSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).UnregisterSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_UnregisterSidecar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).UnregisterSidecar(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParentService_ServiceDesc is the grpc.ServiceDesc for ParentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiquery.v1.ParentService",
	HandlerType: (*ParentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSidecar",
			Handler:    _ParentService_RegisterSidecar_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ParentService_Heartbeat_Handler,
		},
		{
			MethodName: "UnregisterSidecar",
			Handler:    _ParentService_UnregisterSidecar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	SidecarService_Health_FullMethodName             = "/aiquery.v1.SidecarService/Health"
	SidecarService_ExecuteQuery_FullMethodName       = "/aiquery.v1.SidecarService/ExecuteQuery"
	SidecarService_ExecuteDirectQuery_FullMethodName = "/aiquery.v1.SidecarService/ExecuteDirectQuery"
	SidecarService_GetSchema_FullMethodName          = "/aiquery.v1.SidecarService/GetSchema"
)

// SidecarServiceClient is the client API for SidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SidecarService is the gRPC service that each sidecar exposes
// Parent calls these methods to execute queries on the sidecar
type SidecarServiceClient interface {
	// Health check for the sidecar
	Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// ExecuteQuery executes a natural language query (generates SQL with AI)
	// Returns results inline for small datasets, or S3 path for large ones
	ExecuteQuery(ctx context.Context, in *SidecarQueryRequest, opts ...grpc.CallOption) (*SidecarQueryResponse, error)
	// ExecuteDirectQuery executes a pre-generated SQL query (no AI generation)
	// Used for saved queries and dashboard widgets
	ExecuteDirectQuery(ctx context.Context, in *DirectQueryRequest, opts ...grpc.CallOption) (*SidecarQueryResponse, error)
	// GetSchema retrieves database schema
	GetSchema(ctx context.Context, in *SidecarSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
}

type sidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSidecarServiceClient(cc grpc.ClientConnInterface) SidecarServiceClient {
	return &sidecarServiceClient{cc}
}

func (c *sidecarServiceClient) Health(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SidecarService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) ExecuteQuery(ctx context.Context, in *SidecarQueryRequest, opts ...grpc.CallOption) (*SidecarQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SidecarQueryResponse)
	err := c.cc.Invoke(ctx, SidecarService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) ExecuteDirectQuery(ctx context.Context, in *DirectQueryRequest, opts ...grpc.CallOption) (*SidecarQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SidecarQueryResponse)
	err := c.cc.Invoke(ctx, SidecarService_ExecuteDirectQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidecarServiceClient) GetSchema(ctx context.Context, in *SidecarSchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, SidecarService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SidecarServiceServer is the server API for SidecarService service.
// All implementations must embed UnimplementedSidecarServiceServer
// for forward compatibility.
//
// SidecarService is the gRPC service that each sidecar exposes
// Parent calls these methods to execute queries on the sidecar
type SidecarServiceServer interface {
	// Health check for the sidecar
	Health(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// ExecuteQuery executes a natural language query (generates SQL with AI)
	// Returns results inline for small datasets, or S3 path for large ones
	ExecuteQuery(context.Context, *SidecarQueryRequest) (*SidecarQueryResponse, error)
	// ExecuteDirectQuery executes a pre-generated SQL query (no AI generation)
	// Used for saved queries and dashboard widgets
	ExecuteDirectQuery(context.Context, *DirectQueryRequest) (*SidecarQueryResponse, error)
	// GetSchema retrieves database schema
	GetSchema(context.Context, *SidecarSchemaRequest) (*SchemaResponse, error)
	mustEmbedUnimplementedSidecarServiceServer()
}

// UnimplementedSidecarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSidecarServiceServer struct{}

func (UnimplementedSidecarServiceServer) Health(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSidecarServiceServer) ExecuteQuery(context.Context, *SidecarQueryRequest) (*SidecarQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedSidecarServiceServer) ExecuteDirectQuery(context.Context, *DirectQueryRequest) (*SidecarQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteDirectQuery not implemented")
}
func (UnimplementedSidecarServiceServer) GetSchema(context.Context, *SidecarSchemaRequest) (*SchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedSidecarServiceServer) mustEmbedUnimplementedSidecarServiceServer() {}
func (UnimplementedSidecarServiceServer) testEmbeddedByValue()                        {}

// UnsafeSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SidecarServiceServer will
// result in compilation errors.
type UnsafeSidecarServiceServer interface {
	mustEmbedUnimplementedSidecarServiceServer()
}

func RegisterSidecarServiceServer(s grpc.ServiceRegistrar, srv SidecarServiceServer) {
	// If the following call panics, it indicates UnimplementedSidecarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SidecarService_ServiceDesc, srv)
}

func _SidecarService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).Health(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SidecarQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).ExecuteQuery(ctx, req.(*SidecarQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_ExecuteDirectQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).ExecuteDirectQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_ExecuteDirectQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).ExecuteDirectQuery(ctx, req.(*DirectQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SidecarService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SidecarSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidecarServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SidecarService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidecarServiceServer).GetSchema(ctx, req.(*SidecarSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SidecarService_ServiceDesc is the grpc.ServiceDesc for SidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiquery.v1.SidecarService",
	HandlerType: (*SidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _SidecarService_Health_Handler,
		},
		{
			MethodName: "ExecuteQuery",
			Handler:    _SidecarService_ExecuteQuery_Handler,
		},
		{
			MethodName: "ExecuteDirectQuery",
			Handler:    _SidecarService_ExecuteDirectQuery_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _SidecarService_GetSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
