// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: service.proto

package sidecar_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest contains information about a sidecar registering with parent
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	DbInfo        *DatabaseInfo          `protobuf:"bytes,4,opt,name=db_info,json=dbInfo,proto3" json:"db_info,omitempty"`
	Hostname      string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *RegisterRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetDbInfo() *DatabaseInfo {
	if x != nil {
		return x.DbInfo
	}
	return nil
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SidecarId     string                 `protobuf:"bytes,1,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DatabaseInfo describes the database the sidecar is connected to
type DatabaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbType        string                 `protobuf:"bytes,1,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"` // postgres, mysql, dynamodb, mongodb
	DbName        string                 `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	TableCount    int32                  `protobuf:"varint,5,opt,name=table_count,json=tableCount,proto3" json:"table_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseInfo) Reset() {
	*x = DatabaseInfo{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseInfo) ProtoMessage() {}

func (x *DatabaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseInfo.ProtoReflect.Descriptor instead.
func (*DatabaseInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *DatabaseInfo) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *DatabaseInfo) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *DatabaseInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DatabaseInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DatabaseInfo) GetTableCount() int32 {
	if x != nil {
		return x.TableCount
	}
	return 0
}

// HeartbeatRequest is sent periodically by sidecars
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SidecarId     string                 `protobuf:"bytes,1,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // healthy, degraded, unhealthy
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *HealthMetrics         `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetMetrics() *HealthMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// HealthMetrics provides basic health information
type HealthMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveConnections int32                  `protobuf:"varint,1,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	QueriesPerMinute  int32                  `protobuf:"varint,2,opt,name=queries_per_minute,json=queriesPerMinute,proto3" json:"queries_per_minute,omitempty"`
	CpuPercent        float64                `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent     float64                `protobuf:"fixed64,4,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthMetrics) Reset() {
	*x = HealthMetrics{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthMetrics) ProtoMessage() {}

func (x *HealthMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthMetrics.ProtoReflect.Descriptor instead.
func (*HealthMetrics) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *HealthMetrics) GetQueriesPerMinute() int32 {
	if x != nil {
		return x.QueriesPerMinute
	}
	return 0
}

func (x *HealthMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HealthMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

// QueryRequest contains a natural language query
type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SidecarId     string                 `protobuf:"bytes,1,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"` // Natural language query
	Options       *QueryOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRequest) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

func (x *QueryRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type QueryOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RowLimit       int32                  `protobuf:"varint,1,opt,name=row_limit,json=rowLimit,proto3" json:"row_limit,omitempty"`                   // Max rows to return (default 10000)
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Query timeout (default 30)
	UseCache       bool                   `protobuf:"varint,3,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`                   // Whether to use cached results
	Explain        bool                   `protobuf:"varint,4,opt,name=explain,proto3" json:"explain,omitempty"`                                     // Return query explanation
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *QueryOptions) GetRowLimit() int32 {
	if x != nil {
		return x.RowLimit
	}
	return 0
}

func (x *QueryOptions) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *QueryOptions) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

func (x *QueryOptions) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

// QueryResponse contains the generated SQL/query and results
type QueryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryId        string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	GeneratedQuery string                 `protobuf:"bytes,2,opt,name=generated_query,json=generatedQuery,proto3" json:"generated_query,omitempty"` // SQL, PartiQL, or MQL
	Result         *QueryResult           `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata       *QueryMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResponse) GetGeneratedQuery() string {
	if x != nil {
		return x.GeneratedQuery
	}
	return ""
}

func (x *QueryResponse) GetResult() *QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryResponse) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// QueryResult holds the actual data returned
type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	RowCount      int32                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResult) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResult) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResult) GetRowCount() int32 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *Row) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_BytesValue
	//	*Value_TimestampValue
	Value         isValue_Value `protobuf_oneof:"value"`
	IsNull        bool          `protobuf:"varint,7,opt,name=is_null,json=isNull,proto3" json:"is_null,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *Value) GetIsNull() bool {
	if x != nil {
		return x.IsNull
	}
	return false
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_IntValue) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_BytesValue) isValue_Value() {}

func (*Value_TimestampValue) isValue_Value() {}

type QueryMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	DurationMs    int32                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	AiModelUsed   string                 `protobuf:"bytes,3,opt,name=ai_model_used,json=aiModelUsed,proto3" json:"ai_model_used,omitempty"`
	FromCache     bool                   `protobuf:"varint,4,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetadata) Reset() {
	*x = QueryMetadata{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetadata) ProtoMessage() {}

func (x *QueryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetadata.ProtoReflect.Descriptor instead.
func (*QueryMetadata) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *QueryMetadata) GetExecutionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutionTime
	}
	return nil
}

func (x *QueryMetadata) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *QueryMetadata) GetAiModelUsed() string {
	if x != nil {
		return x.AiModelUsed
	}
	return ""
}

func (x *QueryMetadata) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *QueryMetadata) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

// QueryResultChunk for streaming large results
type QueryResultChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	IsFinalChunk  bool                   `protobuf:"varint,4,opt,name=is_final_chunk,json=isFinalChunk,proto3" json:"is_final_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultChunk) Reset() {
	*x = QueryResultChunk{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultChunk) ProtoMessage() {}

func (x *QueryResultChunk) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultChunk.ProtoReflect.Descriptor instead.
func (*QueryResultChunk) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *QueryResultChunk) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResultChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *QueryResultChunk) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResultChunk) GetIsFinalChunk() bool {
	if x != nil {
		return x.IsFinalChunk
	}
	return false
}

// SchemaRequest asks for database schema
type SchemaRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SidecarId         string                 `protobuf:"bytes,1,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"`
	TeamId            string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	IncludeSampleData bool                   `protobuf:"varint,3,opt,name=include_sample_data,json=includeSampleData,proto3" json:"include_sample_data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SchemaRequest) Reset() {
	*x = SchemaRequest{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRequest) ProtoMessage() {}

func (x *SchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRequest.ProtoReflect.Descriptor instead.
func (*SchemaRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *SchemaRequest) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

func (x *SchemaRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SchemaRequest) GetIncludeSampleData() bool {
	if x != nil {
		return x.IncludeSampleData
	}
	return false
}

type SchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaText    string                 `protobuf:"bytes,1,opt,name=schema_text,json=schemaText,proto3" json:"schema_text,omitempty"` // Raw schema as string (for AI context)
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaResponse) Reset() {
	*x = SchemaResponse{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaResponse) ProtoMessage() {}

func (x *SchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaResponse.ProtoReflect.Descriptor instead.
func (*SchemaResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *SchemaResponse) GetSchemaText() string {
	if x != nil {
		return x.SchemaText
	}
	return ""
}

func (x *SchemaResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *SchemaResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type TableSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []*ColumnSchema        `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	RowCount      int64                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	Indexes       []*Index               `protobuf:"bytes,4,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *TableSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableSchema) GetColumns() []*ColumnSchema {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *TableSchema) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *TableSchema) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type ColumnSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	PrimaryKey    bool                   `protobuf:"varint,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	ForeignKey    bool                   `protobuf:"varint,5,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	ForeignTable  string                 `protobuf:"bytes,6,opt,name=foreign_table,json=foreignTable,proto3" json:"foreign_table,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnSchema) Reset() {
	*x = ColumnSchema{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnSchema) ProtoMessage() {}

func (x *ColumnSchema) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnSchema.ProtoReflect.Descriptor instead.
func (*ColumnSchema) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *ColumnSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnSchema) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ColumnSchema) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *ColumnSchema) GetPrimaryKey() bool {
	if x != nil {
		return x.PrimaryKey
	}
	return false
}

func (x *ColumnSchema) GetForeignKey() bool {
	if x != nil {
		return x.ForeignKey
	}
	return false
}

func (x *ColumnSchema) GetForeignTable() string {
	if x != nil {
		return x.ForeignTable
	}
	return ""
}

func (x *ColumnSchema) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type Index struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Unique        bool                   `protobuf:"varint,3,opt,name=unique,proto3" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *Index) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Index) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Index) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

// SaveDashboardRequest saves a dashboard configuration
type SaveDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	DashboardName string                 `protobuf:"bytes,2,opt,name=dashboard_name,json=dashboardName,proto3" json:"dashboard_name,omitempty"`
	Widgets       []*Widget              `protobuf:"bytes,3,rep,name=widgets,proto3" json:"widgets,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDashboardRequest) Reset() {
	*x = SaveDashboardRequest{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDashboardRequest) ProtoMessage() {}

func (x *SaveDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDashboardRequest.ProtoReflect.Descriptor instead.
func (*SaveDashboardRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *SaveDashboardRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *SaveDashboardRequest) GetDashboardName() string {
	if x != nil {
		return x.DashboardName
	}
	return ""
}

func (x *SaveDashboardRequest) GetWidgets() []*Widget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

func (x *SaveDashboardRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SaveDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DashboardId   string                 `protobuf:"bytes,1,opt,name=dashboard_id,json=dashboardId,proto3" json:"dashboard_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDashboardResponse) Reset() {
	*x = SaveDashboardResponse{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDashboardResponse) ProtoMessage() {}

func (x *SaveDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDashboardResponse.ProtoReflect.Descriptor instead.
func (*SaveDashboardResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *SaveDashboardResponse) GetDashboardId() string {
	if x != nil {
		return x.DashboardId
	}
	return ""
}

func (x *SaveDashboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveDashboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Widget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      string                 `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	WidgetType    string                 `protobuf:"bytes,2,opt,name=widget_type,json=widgetType,proto3" json:"widget_type,omitempty"` // table, bar_chart, line_chart, pie_chart, metric
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Widget-specific configuration
	Position      *Position              `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *Widget) GetWidgetId() string {
	if x != nil {
		return x.WidgetId
	}
	return ""
}

func (x *Widget) GetWidgetType() string {
	if x != nil {
		return x.WidgetType
	}
	return ""
}

func (x *Widget) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Widget) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Widget) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Position) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// UnregisterRequest is sent when sidecar shuts down
type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SidecarId     string                 `protobuf:"bytes,1,opt,name=sidecar_id,json=sidecarId,proto3" json:"sidecar_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *UnregisterRequest) GetSidecarId() string {
	if x != nil {
		return x.SidecarId
	}
	return ""
}

func (x *UnregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *UnregisterResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// SidecarQueryRequest is sent from parent to sidecar
type SidecarQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Natural language query
	Options       *QueryOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SidecarQueryRequest) Reset() {
	*x = SidecarQueryRequest{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidecarQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarQueryRequest) ProtoMessage() {}

func (x *SidecarQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarQueryRequest.ProtoReflect.Descriptor instead.
func (*SidecarQueryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *SidecarQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SidecarQueryRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// SidecarQueryResponse is returned from sidecar to parent
type SidecarQueryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryId        string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	GeneratedQuery string                 `protobuf:"bytes,2,opt,name=generated_query,json=generatedQuery,proto3" json:"generated_query,omitempty"` // The SQL/PartiQL/MQL that was generated
	// Results can be returned inline or via S3
	//
	// Types that are valid to be assigned to ResultLocation:
	//
	//	*SidecarQueryResponse_InlineResult
	//	*SidecarQueryResponse_S3Path
	ResultLocation isSidecarQueryResponse_ResultLocation `protobuf_oneof:"result_location"`
	Metadata       *QueryMetadata                        `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Error          string                                `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SidecarQueryResponse) Reset() {
	*x = SidecarQueryResponse{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidecarQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarQueryResponse) ProtoMessage() {}

func (x *SidecarQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarQueryResponse.ProtoReflect.Descriptor instead.
func (*SidecarQueryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *SidecarQueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SidecarQueryResponse) GetGeneratedQuery() string {
	if x != nil {
		return x.GeneratedQuery
	}
	return ""
}

func (x *SidecarQueryResponse) GetResultLocation() isSidecarQueryResponse_ResultLocation {
	if x != nil {
		return x.ResultLocation
	}
	return nil
}

func (x *SidecarQueryResponse) GetInlineResult() *QueryResult {
	if x != nil {
		if x, ok := x.ResultLocation.(*SidecarQueryResponse_InlineResult); ok {
			return x.InlineResult
		}
	}
	return nil
}

func (x *SidecarQueryResponse) GetS3Path() string {
	if x != nil {
		if x, ok := x.ResultLocation.(*SidecarQueryResponse_S3Path); ok {
			return x.S3Path
		}
	}
	return ""
}

func (x *SidecarQueryResponse) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SidecarQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type isSidecarQueryResponse_ResultLocation interface {
	isSidecarQueryResponse_ResultLocation()
}

type SidecarQueryResponse_InlineResult struct {
	InlineResult *QueryResult `protobuf:"bytes,3,opt,name=inline_result,json=inlineResult,proto3,oneof"` // For small results
}

type SidecarQueryResponse_S3Path struct {
	S3Path string `protobuf:"bytes,4,opt,name=s3_path,json=s3Path,proto3,oneof"` // For large results (s3://bucket/key)
}

func (*SidecarQueryResponse_InlineResult) isSidecarQueryResponse_ResultLocation() {}

func (*SidecarQueryResponse_S3Path) isSidecarQueryResponse_ResultLocation() {}

// SidecarSchemaRequest is sent from parent to sidecar
type SidecarSchemaRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IncludeSampleData bool                   `protobuf:"varint,1,opt,name=include_sample_data,json=includeSampleData,proto3" json:"include_sample_data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SidecarSchemaRequest) Reset() {
	*x = SidecarSchemaRequest{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidecarSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarSchemaRequest) ProtoMessage() {}

func (x *SidecarSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarSchemaRequest.ProtoReflect.Descriptor instead.
func (*SidecarSchemaRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *SidecarSchemaRequest) GetIncludeSampleData() bool {
	if x != nil {
		return x.IncludeSampleData
	}
	return false
}

// DirectQueryRequest is sent from parent to sidecar for pre-generated queries
type DirectQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"` // The SQL/PartiQL/MQL to execute directly
	Options       *QueryOptions          `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectQueryRequest) Reset() {
	*x = DirectQueryRequest{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectQueryRequest) ProtoMessage() {}

func (x *DirectQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectQueryRequest.ProtoReflect.Descriptor instead.
func (*DirectQueryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *DirectQueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *DirectQueryRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// HealthCheckRequest for sidecar health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

// HealthCheckResponse returns sidecar health status
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AiProvider    string                 `protobuf:"bytes,3,opt,name=ai_provider,json=aiProvider,proto3" json:"ai_provider,omitempty"`
	AiModel       string                 `protobuf:"bytes,4,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	DbType        string                 `protobuf:"bytes,5,opt,name=db_type,json=dbType,proto3" json:"db_type,omitempty"`
	DbName        string                 `protobuf:"bytes,6,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{30}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthCheckResponse) GetAiProvider() string {
	if x != nil {
		return x.AiProvider
	}
	return ""
}

func (x *HealthCheckResponse) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *HealthCheckResponse) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (x *HealthCheckResponse) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"aiquery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x121\n" +
	"\adb_info\x18\x04 \x01(\v2\x18.aiquery.v1.DatabaseInfoR\x06dbInfo\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\"e\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x01 \x01(\tR\tsidecarId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x89\x01\n" +
	"\fDatabaseInfo\x12\x17\n" +
	"\adb_type\x18\x01 \x01(\tR\x06dbType\x12\x17\n" +
	"\adb_name\x18\x02 \x01(\tR\x06dbName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1f\n" +
	"\vtable_count\x18\x05 \x01(\x05R\n" +
	"tableCount\"\xb8\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x01 \x01(\tR\tsidecarId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\ametrics\x18\x04 \x01(\v2\x19.aiquery.v1.HealthMetricsR\ametrics\"t\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xb4\x01\n" +
	"\rHealthMetrics\x12-\n" +
	"\x12active_connections\x18\x01 \x01(\x05R\x11activeConnections\x12,\n" +
	"\x12queries_per_minute\x18\x02 \x01(\x05R\x10queriesPerMinute\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x04 \x01(\x01R\rmemoryPercent\"\x90\x01\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x01 \x01(\tR\tsidecarId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x122\n" +
	"\aoptions\x18\x04 \x01(\v2\x18.aiquery.v1.QueryOptionsR\aoptions\"\x8b\x01\n" +
	"\fQueryOptions\x12\x1b\n" +
	"\trow_limit\x18\x01 \x01(\x05R\browLimit\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12\x1b\n" +
	"\tuse_cache\x18\x03 \x01(\bR\buseCache\x12\x18\n" +
	"\aexplain\x18\x04 \x01(\bR\aexplain\"\xd1\x01\n" +
	"\rQueryResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12'\n" +
	"\x0fgenerated_query\x18\x02 \x01(\tR\x0egeneratedQuery\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.aiquery.v1.QueryResultR\x06result\x125\n" +
	"\bmetadata\x18\x04 \x01(\v2\x19.aiquery.v1.QueryMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"i\n" +
	"\vQueryResult\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12#\n" +
	"\x04rows\x18\x02 \x03(\v2\x0f.aiquery.v1.RowR\x04rows\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x05R\browCount\"\x88\x01\n" +
	"\x03Row\x123\n" +
	"\x06values\x18\x01 \x03(\v2\x1b.aiquery.v1.Row.ValuesEntryR\x06values\x1aL\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.aiquery.v1.ValueR\x05value:\x028\x01\"\x9d\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12E\n" +
	"\x0ftimestamp_value\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12\x17\n" +
	"\ais_null\x18\a \x01(\bR\x06isNullB\a\n" +
	"\x05value\"\xd7\x01\n" +
	"\rQueryMetadata\x12A\n" +
	"\x0eexecution_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\rexecutionTime\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x05R\n" +
	"durationMs\x12\"\n" +
	"\rai_model_used\x18\x03 \x01(\tR\vaiModelUsed\x12\x1d\n" +
	"\n" +
	"from_cache\x18\x04 \x01(\bR\tfromCache\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\"\x9b\x01\n" +
	"\x10QueryResultChunk\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12#\n" +
	"\x04rows\x18\x03 \x03(\v2\x0f.aiquery.v1.RowR\x04rows\x12$\n" +
	"\x0eis_final_chunk\x18\x04 \x01(\bR\fisFinalChunk\"w\n" +
	"\rSchemaRequest\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x01 \x01(\tR\tsidecarId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12.\n" +
	"\x13include_sample_data\x18\x03 \x01(\bR\x11includeSampleData\"\x97\x01\n" +
	"\x0eSchemaResponse\x12\x1f\n" +
	"\vschema_text\x18\x01 \x01(\tR\n" +
	"schemaText\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\tR\rschemaVersion\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x9f\x01\n" +
	"\vTableSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\acolumns\x18\x02 \x03(\v2\x18.aiquery.v1.ColumnSchemaR\acolumns\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x03R\browCount\x12+\n" +
	"\aindexes\x18\x04 \x03(\v2\x11.aiquery.v1.IndexR\aindexes\"\xe7\x01\n" +
	"\fColumnSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x01(\bR\n" +
	"primaryKey\x12\x1f\n" +
	"\vforeign_key\x18\x05 \x01(\bR\n" +
	"foreignKey\x12#\n" +
	"\rforeign_table\x18\x06 \x01(\tR\fforeignTable\x12#\n" +
	"\rdefault_value\x18\a \x01(\tR\fdefaultValue\"M\n" +
	"\x05Index\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\"\x8d\x02\n" +
	"\x14SaveDashboardRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\x12%\n" +
	"\x0edashboard_name\x18\x02 \x01(\tR\rdashboardName\x12,\n" +
	"\awidgets\x18\x03 \x03(\v2\x12.aiquery.v1.WidgetR\awidgets\x12J\n" +
	"\bmetadata\x18\x04 \x03(\v2..aiquery.v1.SaveDashboardRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x15SaveDashboardResponse\x12!\n" +
	"\fdashboard_id\x18\x01 \x01(\tR\vdashboardId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x81\x02\n" +
	"\x06Widget\x12\x1b\n" +
	"\twidget_id\x18\x01 \x01(\tR\bwidgetId\x12\x1f\n" +
	"\vwidget_type\x18\x02 \x01(\tR\n" +
	"widgetType\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x126\n" +
	"\x06config\x18\x04 \x03(\v2\x1e.aiquery.v1.Widget.ConfigEntryR\x06config\x120\n" +
	"\bposition\x18\x05 \x01(\v2\x14.aiquery.v1.PositionR\bposition\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"J\n" +
	"\x11UnregisterRequest\x12\x1d\n" +
	"\n" +
	"sidecar_id\x18\x01 \x01(\tR\tsidecarId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"8\n" +
	"\x12UnregisterResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"_\n" +
	"\x13SidecarQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\aoptions\x18\x02 \x01(\v2\x18.aiquery.v1.QueryOptionsR\aoptions\"\x95\x02\n" +
	"\x14SidecarQueryResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12'\n" +
	"\x0fgenerated_query\x18\x02 \x01(\tR\x0egeneratedQuery\x12>\n" +
	"\rinline_result\x18\x03 \x01(\v2\x17.aiquery.v1.QueryResultH\x00R\finlineResult\x12\x19\n" +
	"\as3_path\x18\x04 \x01(\tH\x00R\x06s3Path\x125\n" +
	"\bmetadata\x18\x05 \x01(\v2\x19.aiquery.v1.QueryMetadataR\bmetadata\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05errorB\x11\n" +
	"\x0fresult_location\"F\n" +
	"\x14SidecarSchemaRequest\x12.\n" +
	"\x13include_sample_data\x18\x01 \x01(\bR\x11includeSampleData\"Z\n" +
	"\x12DirectQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x122\n" +
	"\aoptions\x18\x02 \x01(\v2\x18.aiquery.v1.QueryOptionsR\aoptions\"\x14\n" +
	"\x12HealthCheckRequest\"\xd5\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vai_provider\x18\x03 \x01(\tR\n" +
	"aiProvider\x12\x19\n" +
	"\bai_model\x18\x04 \x01(\tR\aaiModel\x12\x17\n" +
	"\adb_type\x18\x05 \x01(\tR\x06dbType\x12\x17\n" +
	"\adb_name\x18\x06 \x01(\tR\x06dbName2\xfb\x01\n" +
	"\rParentService\x12L\n" +
	"\x0fRegisterSidecar\x12\x1b.aiquery.v1.RegisterRequest\x1a\x1c.aiquery.v1.RegisterResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.aiquery.v1.HeartbeatRequest\x1a\x1d.aiquery.v1.HeartbeatResponse\x12R\n" +
	"\x11UnregisterSidecar\x12\x1d.aiquery.v1.UnregisterRequest\x1a\x1e.aiquery.v1.UnregisterResponse2\xd1\x02\n" +
	"\x0eSidecarService\x12I\n" +
	"\x06Health\x12\x1e.aiquery.v1.HealthCheckRequest\x1a\x1f.aiquery.v1.HealthCheckResponse\x12Q\n" +
	"\fExecuteQuery\x12\x1f.aiquery.v1.SidecarQueryRequest\x1a .aiquery.v1.SidecarQueryResponse\x12V\n" +
	"\x12ExecuteDirectQuery\x12\x1e.aiquery.v1.DirectQueryRequest\x1a .aiquery.v1.SidecarQueryResponse\x12I\n" +
	"\tGetSchema\x12 .aiquery.v1.SidecarSchemaRequest\x1a\x1a.aiquery.v1.SchemaResponseB5Z3github.com/notsoMySQL/sidecar-client;sidecar_clientb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: aiquery.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 1: aiquery.v1.RegisterResponse
	(*DatabaseInfo)(nil),          // 2: aiquery.v1.DatabaseInfo
	(*HeartbeatRequest)(nil),      // 3: aiquery.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: aiquery.v1.HeartbeatResponse
	(*HealthMetrics)(nil),         // 5: aiquery.v1.HealthMetrics
	(*QueryRequest)(nil),          // 6: aiquery.v1.QueryRequest
	(*QueryOptions)(nil),          // 7: aiquery.v1.QueryOptions
	(*QueryResponse)(nil),         // 8: aiquery.v1.QueryResponse
	(*QueryResult)(nil),           // 9: aiquery.v1.QueryResult
	(*Row)(nil),                   // 10: aiquery.v1.Row
	(*Value)(nil),                 // 11: aiquery.v1.Value
	(*QueryMetadata)(nil),         // 12: aiquery.v1.QueryMetadata
	(*QueryResultChunk)(nil),      // 13: aiquery.v1.QueryResultChunk
	(*SchemaRequest)(nil),         // 14: aiquery.v1.SchemaRequest
	(*SchemaResponse)(nil),        // 15: aiquery.v1.SchemaResponse
	(*TableSchema)(nil),           // 16: aiquery.v1.TableSchema
	(*ColumnSchema)(nil),          // 17: aiquery.v1.ColumnSchema
	(*Index)(nil),                 // 18: aiquery.v1.Index
	(*SaveDashboardRequest)(nil),  // 19: aiquery.v1.SaveDashboardRequest
	(*SaveDashboardResponse)(nil), // 20: aiquery.v1.SaveDashboardResponse
	(*Widget)(nil),                // 21: aiquery.v1.Widget
	(*Position)(nil),              // 22: aiquery.v1.Position
	(*UnregisterRequest)(nil),     // 23: aiquery.v1.UnregisterRequest
	(*UnregisterResponse)(nil),    // 24: aiquery.v1.UnregisterResponse
	(*SidecarQueryRequest)(nil),   // 25: aiquery.v1.SidecarQueryRequest
	(*SidecarQueryResponse)(nil),  // 26: aiquery.v1.SidecarQueryResponse
	(*SidecarSchemaRequest)(nil),  // 27: aiquery.v1.SidecarSchemaRequest
	(*DirectQueryRequest)(nil),    // 28: aiquery.v1.DirectQueryRequest
	(*HealthCheckRequest)(nil),    // 29: aiquery.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 30: aiquery.v1.HealthCheckResponse
	nil,                           // 31: aiquery.v1.Row.ValuesEntry
	nil,                           // 32: aiquery.v1.SaveDashboardRequest.MetadataEntry
	nil,                           // 33: aiquery.v1.Widget.ConfigEntry
	(*timestamppb.Timestamp)(nil), // 34: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	2,  // 0: aiquery.v1.RegisterRequest.db_info:type_name -> aiquery.v1.DatabaseInfo
	34, // 1: aiquery.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 2: aiquery.v1.HeartbeatRequest.metrics:type_name -> aiquery.v1.HealthMetrics
	34, // 3: aiquery.v1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	7,  // 4: aiquery.v1.QueryRequest.options:type_name -> aiquery.v1.QueryOptions
	9,  // 5: aiquery.v1.QueryResponse.result:type_name -> aiquery.v1.QueryResult
	12, // 6: aiquery.v1.QueryResponse.metadata:type_name -> aiquery.v1.QueryMetadata
	10, // 7: aiquery.v1.QueryResult.rows:type_name -> aiquery.v1.Row
	31, // 8: aiquery.v1.Row.values:type_name -> aiquery.v1.Row.ValuesEntry
	34, // 9: aiquery.v1.Value.timestamp_value:type_name -> google.protobuf.Timestamp
	34, // 10: aiquery.v1.QueryMetadata.execution_time:type_name -> google.protobuf.Timestamp
	10, // 11: aiquery.v1.QueryResultChunk.rows:type_name -> aiquery.v1.Row
	34, // 12: aiquery.v1.SchemaResponse.last_updated:type_name -> google.protobuf.Timestamp
	17, // 13: aiquery.v1.TableSchema.columns:type_name -> aiquery.v1.ColumnSchema
	18, // 14: aiquery.v1.TableSchema.indexes:type_name -> aiquery.v1.Index
	21, // 15: aiquery.v1.SaveDashboardRequest.widgets:type_name -> aiquery.v1.Widget
	32, // 16: aiquery.v1.SaveDashboardRequest.metadata:type_name -> aiquery.v1.SaveDashboardRequest.MetadataEntry
	33, // 17: aiquery.v1.Widget.config:type_name -> aiquery.v1.Widget.ConfigEntry
	22, // 18: aiquery.v1.Widget.position:type_name -> aiquery.v1.Position
	7,  // 19: aiquery.v1.SidecarQueryRequest.options:type_name -> aiquery.v1.QueryOptions
	9,  // 20: aiquery.v1.SidecarQueryResponse.inline_result:type_name -> aiquery.v1.QueryResult
	12, // 21: aiquery.v1.SidecarQueryResponse.metadata:type_name -> aiquery.v1.QueryMetadata
	7,  // 22: aiquery.v1.DirectQueryRequest.options:type_name -> aiquery.v1.QueryOptions
	34, // 23: aiquery.v1.HealthCheckResponse.timestamp:type_name -> google.protobuf.Timestamp
	11, // 24: aiquery.v1.Row.ValuesEntry.value:type_name -> aiquery.v1.Value
	0,  // 25: aiquery.v1.ParentService.RegisterSidecar:input_type -> aiquery.v1.RegisterRequest
	3,  // 26: aiquery.v1.ParentService.Heartbeat:input_type -> aiquery.v1.HeartbeatRequest
	23, // 27: aiquery.v1.ParentService.UnregisterSidecar:input_type -> aiquery.v1.UnregisterRequest
	29, // 28: aiquery.v1.SidecarService.Health:input_type -> aiquery.v1.HealthCheckRequest
	25, // 29: aiquery.v1.SidecarService.ExecuteQuery:input_type -> aiquery.v1.SidecarQueryRequest
	28, // 30: aiquery.v1.SidecarService.ExecuteDirectQuery:input_type -> aiquery.v1.DirectQueryRequest
	27, // 31: aiquery.v1.SidecarService.GetSchema:input_type -> aiquery.v1.SidecarSchemaRequest
	1,  // 32: aiquery.v1.ParentService.RegisterSidecar:output_type -> aiquery.v1.RegisterResponse
	4,  // 33: aiquery.v1.ParentService.Heartbeat:output_type -> aiquery.v1.HeartbeatResponse
	24, // 34: aiquery.v1.ParentService.UnregisterSidecar:output_type -> aiquery.v1.UnregisterResponse
	30, // 35: aiquery.v1.SidecarService.Health:output_type -> aiquery.v1.HealthCheckResponse
	26, // 36: aiquery.v1.SidecarService.ExecuteQuery:output_type -> aiquery.v1.SidecarQueryResponse
	26, // 37: aiquery.v1.SidecarService.ExecuteDirectQuery:output_type -> aiquery.v1.SidecarQueryResponse
	15, // 38: aiquery.v1.SidecarService.GetSchema:output_type -> aiquery.v1.SchemaResponse
	32, // [32:39] is the sub-list for method output_type
	25, // [25:32] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[11].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_TimestampValue)(nil),
	}
	file_service_proto_msgTypes[26].OneofWrappers = []any{
		(*SidecarQueryResponse_InlineResult)(nil),
		(*SidecarQueryResponse_S3Path)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
