// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/aiquery/v1/service.proto

package aiquery

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParentService_RegisterSidecar_FullMethodName    = "/aiquery.v1.ParentService/RegisterSidecar"
	ParentService_Heartbeat_FullMethodName          = "/aiquery.v1.ParentService/Heartbeat"
	ParentService_ExecuteQuery_FullMethodName       = "/aiquery.v1.ParentService/ExecuteQuery"
	ParentService_StreamQueryResults_FullMethodName = "/aiquery.v1.ParentService/StreamQueryResults"
	ParentService_GetSchema_FullMethodName          = "/aiquery.v1.ParentService/GetSchema"
	ParentService_SaveDashboard_FullMethodName      = "/aiquery.v1.ParentService/SaveDashboard"
	ParentService_UnregisterSidecar_FullMethodName  = "/aiquery.v1.ParentService/UnregisterSidecar"
)

// ParentServiceClient is the client API for ParentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ParentService is the gRPC service that sidecars connect to
type ParentServiceClient interface {
	// RegisterSidecar is called when a sidecar starts up
	RegisterSidecar(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat is called periodically to maintain connection
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// ExecuteQuery executes a natural language query and returns results
	ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// StreamQueryResults streams large result sets
	StreamQueryResults(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultChunk], error)
	// GetSchema retrieves database schema information
	GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error)
	// SaveDashboard saves a dashboard configuration
	SaveDashboard(ctx context.Context, in *SaveDashboardRequest, opts ...grpc.CallOption) (*SaveDashboardResponse, error)
	// UnregisterSidecar is called when a sidecar shuts down gracefully
	UnregisterSidecar(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
}

type parentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParentServiceClient(cc grpc.ClientConnInterface) ParentServiceClient {
	return &parentServiceClient{cc}
}

func (c *parentServiceClient) RegisterSidecar(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ParentService_RegisterSidecar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ParentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentServiceClient) ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, ParentService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentServiceClient) StreamQueryResults(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ParentService_ServiceDesc.Streams[0], ParentService_StreamQueryResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResultChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParentService_StreamQueryResultsClient = grpc.ServerStreamingClient[QueryResultChunk]

func (c *parentServiceClient) GetSchema(ctx context.Context, in *SchemaRequest, opts ...grpc.CallOption) (*SchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SchemaResponse)
	err := c.cc.Invoke(ctx, ParentService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentServiceClient) SaveDashboard(ctx context.Context, in *SaveDashboardRequest, opts ...grpc.CallOption) (*SaveDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveDashboardResponse)
	err := c.cc.Invoke(ctx, ParentService_SaveDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parentServiceClient) UnregisterSidecar(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, ParentService_UnregisterSidecar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParentServiceServer is the server API for ParentService service.
// All implementations must embed UnimplementedParentServiceServer
// for forward compatibility.
//
// ParentService is the gRPC service that sidecars connect to
type ParentServiceServer interface {
	// RegisterSidecar is called when a sidecar starts up
	RegisterSidecar(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat is called periodically to maintain connection
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// ExecuteQuery executes a natural language query and returns results
	ExecuteQuery(context.Context, *QueryRequest) (*QueryResponse, error)
	// StreamQueryResults streams large result sets
	StreamQueryResults(*QueryRequest, grpc.ServerStreamingServer[QueryResultChunk]) error
	// GetSchema retrieves database schema information
	GetSchema(context.Context, *SchemaRequest) (*SchemaResponse, error)
	// SaveDashboard saves a dashboard configuration
	SaveDashboard(context.Context, *SaveDashboardRequest) (*SaveDashboardResponse, error)
	// UnregisterSidecar is called when a sidecar shuts down gracefully
	UnregisterSidecar(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	mustEmbedUnimplementedParentServiceServer()
}

// UnimplementedParentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParentServiceServer struct{}

func (UnimplementedParentServiceServer) RegisterSidecar(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSidecar not implemented")
}
func (UnimplementedParentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedParentServiceServer) ExecuteQuery(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedParentServiceServer) StreamQueryResults(*QueryRequest, grpc.ServerStreamingServer[QueryResultChunk]) error {
	return status.Errorf(codes.Unimplemented, "method StreamQueryResults not implemented")
}
func (UnimplementedParentServiceServer) GetSchema(context.Context, *SchemaRequest) (*SchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedParentServiceServer) SaveDashboard(context.Context, *SaveDashboardRequest) (*SaveDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDashboard not implemented")
}
func (UnimplementedParentServiceServer) UnregisterSidecar(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterSidecar not implemented")
}
func (UnimplementedParentServiceServer) mustEmbedUnimplementedParentServiceServer() {}
func (UnimplementedParentServiceServer) testEmbeddedByValue()                       {}

// UnsafeParentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParentServiceServer will
// result in compilation errors.
type UnsafeParentServiceServer interface {
	mustEmbedUnimplementedParentServiceServer()
}

func RegisterParentServiceServer(s grpc.ServiceRegistrar, srv ParentServiceServer) {
	// If the following call pancis, it indicates UnimplementedParentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParentService_ServiceDesc, srv)
}

func _ParentService_RegisterSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).RegisterSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_RegisterSidecar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).RegisterSidecar(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParentService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).ExecuteQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParentService_StreamQueryResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ParentServiceServer).StreamQueryResults(m, &grpc.GenericServerStream[QueryRequest, QueryResultChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ParentService_StreamQueryResultsServer = grpc.ServerStreamingServer[QueryResultChunk]

func _ParentService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).GetSchema(ctx, req.(*SchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParentService_SaveDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).SaveDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_SaveDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).SaveDashboard(ctx, req.(*SaveDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParentService_UnregisterSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParentServiceServer).UnregisterSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParentService_UnregisterSidecar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParentServiceServer).UnregisterSidecar(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParentService_ServiceDesc is the grpc.ServiceDesc for ParentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiquery.v1.ParentService",
	HandlerType: (*ParentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSidecar",
			Handler:    _ParentService_RegisterSidecar_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ParentService_Heartbeat_Handler,
		},
		{
			MethodName: "ExecuteQuery",
			Handler:    _ParentService_ExecuteQuery_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _ParentService_GetSchema_Handler,
		},
		{
			MethodName: "SaveDashboard",
			Handler:    _ParentService_SaveDashboard_Handler,
		},
		{
			MethodName: "UnregisterSidecar",
			Handler:    _ParentService_UnregisterSidecar_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamQueryResults",
			Handler:       _ParentService_StreamQueryResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/aiquery/v1/service.proto",
}
